---
title: "COVID Excess Mortality"
author:
- name: Kieran Healy
  url: https://kieranhealy.org
  affiliation: Duke University
  affiliation_url: https://sociology.duke.edu
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  pdf_document:
    template: ~/.pandoc/templates/rmd-latex.template
  distill::distill_article:
    highlight: tango
toc: yes
description: |
  Looking at CDC Data on Mortality.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      dpi =  200,
                      fig.retina = 2)
```

```{r, message=FALSE}
library(tidyverse)
library(janitor)

###-------------------------------------------------
### Not needed to draw the graphs
library(showtext)
showtext_auto()

library(myriad)
import_myriad_semi_ttf()

theme_set(theme_myriad_new())
###-------------------------------------------------
```

```{r, message = FALSE}
## https://kjhealy.github.io/covdata
library(covdata)
```


```{r}

states <- nchs_wdc %>% 
  select(jurisdiction) %>% 
  unique()

```

# Counting Excess Deaths by Jurisdiction

- CDC data, using March 1 to Nov 7th (Epi weeks 9 to 45) as the period.

```{r}

start_week <- 9
end_week <- 45

df_yr <- nchs_wdc %>%
  filter(year > 2014,
         week >= start_week & 
         week <= end_week) %>% 
  group_by(jurisdiction, cause, year) %>%
  summarize(period_deaths = sum(n, na.rm = TRUE)) 


baseline_deaths <- nchs_wdc %>% 
  filter(year %in% c(2015:2019),
         week >= start_week & 
         week <= end_week) %>%
  group_by(jurisdiction, year, cause) %>%
  summarize(total_n = sum(n, na.rm = TRUE)) %>%
  group_by(jurisdiction, cause) %>%
  summarize(baseline = mean(total_n, na.rm = TRUE), 
            baseline_sd = sd(total_n, na.rm = TRUE)) 

df_excess <- left_join(df_yr, baseline_deaths) %>%
  mutate(excess = period_deaths - baseline, 
         pct_excess = (excess / period_deaths)*100, 
         pct_sd = (baseline_sd/baseline)*100) %>%
  rename(deaths = period_deaths)

df_meds <- df_excess %>%
  summarize(med = median(pct_excess))

```

```{r}

df_sd <- df_excess %>%
  filter(cause %nin% c("COVID-19 Underlying", "COVID-19 Multiple cause", "Other")) %>%
  select(jurisdiction, cause, pct_sd) %>%
  slice(1) %>% 
  mutate(lwr = -2*pct_sd, 
         upr = 2*pct_sd) %>%
  left_join(df_meds)

out <- df_excess %>% 
  filter(jurisdiction == "United States") %>%
  filter(cause %nin% c("COVID-19 Underlying", "COVID-19 Multiple cause", "Other")) %>%
  mutate(yr_ind = ifelse(year == 2020, TRUE, FALSE)) %>%
  ggplot(aes(x = pct_excess/100, y = reorder(cause, pct_excess, median), color = yr_ind, shape = yr_ind, group = year)) + 
  geom_linerange(data = subset(df_sd, jurisdiction == "United States"), 
                 mapping = aes(xmin = lwr/100, xmax = upr/100, y = reorder(cause, med)), 
                 color = "lightblue1", alpha = 0.7, inherit.aes = FALSE, size = 3) + 
  geom_vline(xintercept = 0, color = "black") + 
  geom_jitter(size = 2, position = position_jitter(height = 0.05)) +
  scale_color_manual(values = c("gray50", "firebrick"), 
                     labels = c("2015-2019", "2020")) + 
 scale_shape_manual(values = c(16, 17),
                    labels = c("2015-2019", "2020")) +  
  scale_x_continuous(breaks = c(-10, -5, 0, 5, 10, 15, 20)/100, labels = scales::percent_format(accuracy = 1)) + 
  labs(x = "Percent above or below the average number of deaths for 2015 to 2019", 
       y = NULL, 
       color = "Years", 
       shape = "Years",
       title = "Excess Deaths in the U.S. from March 1st to November 7th",
       subtitle = "Selected Causes. Individual deaths may be due to more than one cause.",
       caption = "Data: CDC. Calculations and Graph: @kjhealy")



print(out)
ggsave(filename = "figures/excess_by_cause.pdf", out, height = 4.25, width = 7)
ggsave(filename = "figures/excess_by_cause.png", out, height = 4.25, width = 7)

```



```{r}
excess_count <- df_excess %>%
  filter(year == 2020 &
           cause %in% c("All Cause", "COVID-19 Multiple cause")) 

excess_table <- excess_count %>%
  mutate(col_cause = janitor::make_clean_names(cause)) %>%
  select(jurisdiction, col_cause, deaths:pct_excess) %>%
  group_by(jurisdiction) %>%
  select(-cause) %>%
  pivot_wider(names_from = col_cause, values_from = deaths:pct_excess) %>%
  select(-pct_excess_covid_19_multiple_cause, -excess_covid_19_multiple_cause, -baseline_covid_19_multiple_cause, 
         -baseline_sd_covid_19_multiple_cause)

colnames(excess_table) <- c("jurisdiction", "all_cause", "covid", "baseline", "baseline_sd", "excess", "pct_excess")


excess_table <- excess_table %>%
  mutate(deficit = excess - covid, 
         pct_covid = (covid / all_cause) * 100, 
         pct_deficit = (deficit / all_cause) * 100) %>%
  select(jurisdiction, all_cause, baseline, baseline_sd, excess, covid, deficit, everything()) 

excess_table %>% 
  filter(jurisdiction == "United States") %>%
  pivot_longer( all_cause:pct_deficit, names_to = "measure", values_to = "value")

```

# State Level Pictures

- CDC data, using March 1 to November 7 (Epi weeks 9 to 45) as the period.

```{r, fig.width = 7, fig.height=7}
library(ggalt)

out <- excess_table %>%
  filter(jurisdiction != "United States") %>%
  ggplot(aes(y = pct_excess, x = reorder(jurisdiction, pct_excess))) + 
  geom_lollipop(color = "gray70", point.colour = "black") + 
  coord_flip() + 
  labs(y = "Percent Difference from 2015-2019 average", 
       x = NULL, 
       title = paste0("Excess Deaths by Jurisdiction, Weeks ", start_week, "--", end_week), 
       subtitle = "Excess is defined as 2020 All-Cause count minus 2015-2019 All-Cause average")

print(out)
ggsave(filename = "figures/excess_state.pdf", out, height = 7, width = 7)


```

```{r, fig.width = 7, fig.height=7}
out <- excess_table %>%
  filter(jurisdiction != "United States") %>%
  ggplot(aes(y = pct_covid, x = reorder(jurisdiction, pct_covid))) + 
  geom_lollipop(color = "gray70", point.colour = "black") + 
  coord_flip() + 
  labs(y = "Percent", 
       x = NULL, 
       title = "COVID-19 Recorded Deaths as a Percentage of All-Cause Mortality", 
       subtitle = paste0("Weeks ", start_week, " to ", end_week, " of 2020"), 
       caption = "Data: CDC. Calculations and graph: @kjhealy")

print(out)
ggsave(filename = "figures/excess_pct_covid_of_all_state.pdf", out, height = 7, width = 7)

```


```{r, fig.width = 7, fig.height=7}
out <- excess_table %>%
  filter(jurisdiction != "United States") %>%
  ggplot(aes(y = deficit, x = reorder(jurisdiction, deficit))) + 
  geom_lollipop(color = "gray70", point.colour = "black") + 
  coord_flip() + 
  labs(y = "Excess deaths remaining after subtracting COVID deaths", 
       x = NULL, 
      title = paste0("Implied Deficit by Jurisdiction, Weeks ", start_week, "--", end_week))

print(out)
ggsave(filename = "figures/excess_minus_covid_n_state.pdf", out, height = 7, width = 7)


```

```{r, fig.width = 7, fig.height=7}

out <- excess_table %>%
  filter(jurisdiction %nin% c("United States", "Connecticut", "North Carolina", "West Virginia")) %>%
  ggplot(aes(y = pct_deficit, x = reorder(jurisdiction, pct_deficit))) + 
  geom_lollipop(color = "gray70", point.colour = "black") + 
  coord_flip() + 
  labs(y = "Percent of All Cause Mortality", 
       x = NULL, 
       title = "Non-COVID Excess Deaths as a percentage of All-Cause Mortality",
       subtitle = paste0("Weeks ", start_week, " to ", end_week, " of 2020. Excludes CT, NC, and WV due to lags in provisional counts in recent weeks."), 
       caption = "Data: CDC. Calculations and graph: @kjhealy")

print(out)
ggsave(filename = "figures/excess_minus_pct_covid_state.pdf", out, height = 7, width = 7)
ggsave(filename = "figures/excess_minus_pct_covid_state.png", out, height = 7, width = 7)


```

```{r}
excess_table %>%
  filter(jurisdiction == "New York City")
```


```{r}
knitr::kable(excess_table, digits = 2) 
  
```


### State Level

```{r}

df_state_meds <- df_excess %>%
  summarize(med = median(pct_excess))

df_state_sd <- df_excess %>%
  filter(cause %nin% c("COVID-19 Underlying", "COVID-19 Multiple cause", "Other")) %>%
  group_by(jurisdiction, cause) %>% 
  slice(1) %>%
  select(cause, pct_sd) %>%
  mutate(lwr = -2*pct_sd, 
         upr = 2*pct_sd) %>%
  left_join(df_state_meds)



df_state_excess <- left_join(df_excess, df_state_sd)

out <- df_state_excess %>% 
   filter(cause %in% c("Alzheimer's", 
                       "Diabetes", 
                       "Influenza and Pneumonia", 
                       "Cerebrovascular Diseases", 
                       "Diseases of the Heart", 
                       "Cancer", "Chronic Lower Respiratory Diseases",
                       "All Cause")) %>% 
   filter(jurisdiction %in% c("United States", "New York", 
                              "New York City", "New Jersey", 
                              "Florida", "Michigan", "Washington",
                              "Virginia", "Arizona",
                              "California", "Pennsylvania", 
                              "Georgia", "Ohio", 
                              "Illinois")) %>% 
  mutate(yr_ind = ifelse(year == 2020, TRUE, FALSE)) %>%
  ggplot(aes(x = pct_excess/100, 
             y = reorder(jurisdiction, pct_excess), 
             color = yr_ind, shape = yr_ind, group = year)) + 
  geom_linerange(mapping = aes(xmin = lwr/100, 
                               xmax = upr/100, 
                               y = reorder(jurisdiction, pct_excess, mean, na.rm = TRUE)), 
                 color = "lightblue1", alpha = 0.7, size = 3) + 
  geom_vline(xintercept = 0, color = "black") + 
  geom_jitter(size = 2, position = position_jitter(height = 0.05)) +
  scale_color_manual(values = c("gray50", "firebrick"), 
                     labels = c("2015-2019", "2020")) + 
  scale_shape_manual(values = c(16, 17),
                      labels = c("2015-2019", "2020")) +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1)) + 
  guides(shape = guide_legend(keywidth = 0.15), 
         color = guide_legend(keywidth = 0.15)) + 
  labs(x = "Percent above or below the average number of deaths, Mar 1 to Nov 7 2015-2019", 
       y = NULL, 
       color = "Years",
       shape = "Years",
       title = "  Excess deaths for selected jurisdictions and causes, March 1st to November 7th",
       subtitle = "  Blue bars show +/- 2 standard deviations around the 2015-2019 mean for each cause. Individual deaths may be recorded as having more than one cause.",
       caption = "Data: CDC. Calculations and Graph: Kieran Healy / @kjhealy") +
 facet_wrap(~reorder(cause, -pct_excess), ncol = 2) 


out <- out + theme(strip.text = element_text(size = rel(1.1), hjust = 0), 
          legend.justification = "left", 
          panel.border  = element_rect(color = "gray90", size = rel(0.8), linetype="solid", fill = NA),
          axis.text.y = element_text(face = c(rep("plain", 5), "bold", rep("plain", 6))))



ggsave(filename = "figures/excess_by_cause_jurisdictions.pdf", out, height = 12, width = 12)
ggsave(filename = "figures/excess_by_cause_jurisdictions.png", out, height = 12, width = 12, dpi = 200)

```

```{r}

out <- df_state_excess %>% 
   filter(cause %in% c("All Cause")) %>% 
  mutate(yr_ind = ifelse(year == 2020, TRUE, FALSE)) %>%
  ggplot(aes(x = pct_excess/100, 
             y = reorder(jurisdiction, deaths), 
             color = yr_ind, shape = yr_ind, group = year)) + 
  geom_linerange(mapping = aes(xmin = lwr/100, 
                               xmax = upr/100, 
                               y = reorder(jurisdiction, deaths, mean, na.rm = TRUE)), 
                 color = "lightblue1", alpha = 0.7, size = 3) + 
  geom_vline(xintercept = 0, color = "black") + 
  geom_jitter(size = 2, position = position_jitter(height = 0.05)) +
  scale_color_manual(values = c("gray50", "firebrick"), 
                     labels = c("2015-2019", "2020")) + 
  scale_shape_manual(values = c(16, 17),
                      labels = c("2015-2019", "2020")) +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1), 
                     breaks = seq(-0.2, 0.5, 0.1), 
                     position = "top") + 
  guides(shape = guide_legend(keywidth = 0.15), 
         color = guide_legend(keywidth = 0.15)) + 
  labs(x = "   Percent above or below the average number of deaths, March 1st to November 7th 2015-2019", 
       y = NULL, 
       color = "Years",
       shape = "Years",
       title = "  All-Cause Excess Mortality by Jurisdiction, March 1st to November 7th",
       subtitle = "  Blue bars show +/- 2 standard deviations around the 2015-2019 mean.\n  Jurisdictions ordered from highest to lowest all-cause mortality count.\n  The low NC and WV counts are an artifact of reporting delays.",
       caption = "Data: CDC. Calculations and Graph: Kieran Healy / @kjhealy") 

out <- out + theme(legend.justification = "left", 
          panel.border  = element_rect(color = "gray90", size = rel(0.8), linetype="solid", fill = NA),
          axis.text.y = element_text(face = c(rep("plain", 53), "bold")), 
          axis.title.x = element_text(hjust = 0, size = rel(0.9)), 
          plot.title = element_text(size = rel(1.35)))

ggsave(filename = "figures/excess_all_cause_by_jurisdiction.pdf", out, height = 11, width = 8)
ggsave(filename = "figures/excess_all_cause_by_jurisdiction.png", out, height = 11, width = 8, dpi = 200)

```



